version: '3.7'
services:
  php:
    build: ./docker/php
    working_dir: /work
    volumes:
      - .:/work

  nginx:
    build: ./docker/nginx
    working_dir: /work
    ports:
      - ${HOST_PORT_HTTP:-8080}:80
    volumes:
      - .:/work

