version: '3.7'
services:
  php:
    build: ./docker/php
    working_dir: /work/app
    volumes:
      - .:/work:delegated

  nginx:
    build: ./docker/nginx
    working_dir: /work
    ports:
      - ${HOST_PORT_HTTP:-8080}:80
    volumes:
      - .:/work:delegated

  node:
    build: ./docker/node
    working_dir: /work/app
    entrypoint: npx encore dev --watch --config webpack.config.ssr.js
    volumes:
      - .:/work
      - node_modules:/work/app/node_modules

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  mysql:
    driver: local
  node_modules:
    driver: local
