index:
   path: /
   controller: App\Controller\IndexController::index

runtimes:
   path: /runtimes
   controller: App\Controller\IndexController::runtimes

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number